spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni_clock?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: RElBUllfQU5EX0NPTU1VTklUWV9QUk9KRUNUX0RBV05BUllfQURNSU5fU0VDUkVUX0tFWQ==
  access-token-expiration-time: 1800000
  refresh-token-expiration-time: 604800000

logging:
  level:
    com.uniclock.backend.global.security: DEBUG
    com.uniclock.backend: INFO
